### ISSUE TITLE
[7-1] group_concat 사용시 설정된 메모리 초과하게 되면 disk에 쓰는가?

### ISSUE THREAD

**Issue by JungleKim** [chocolate-factory/realmysql-study#1]
메모리를 초과하면 Warning이 나온다고 하는데, Disk에 쓰면서 처리한 후 Warning을 보여주는 건지 확인.

**Comment by TaeGuNi** [comment]
https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_group-concat

group_concat은 단순히 문자열 함수에 불과 합니다. 합쳐진 문자열 길이에 제한을 변수로 조절할 수 있을 뿐입니다.
이렇게 가공된 결과 셋은 출력전 임시테이블에 저장하게 되는데, 이 때, 시스템 변수로 할당된 메모리에 용량이 넘어가면 디스크에서 작성이 되게 됩니다. 아래 시스템 변수의 설명을 확인해보면 도움이 될 수 있습니다.
group by, order by, inline view 구문등 많은 쿼리에서 실제로 데이터 가공을 위해서 쿼리 수행시 tmp_table을  작성하며, 결과셋의 크기가 tmp_table_size 또는 max_heap_table_size의 설정값을 넘어가면, 디스크에 작성하게 됩니다.

생각 해볼 사항으로는 그럼 tmp_table_size의 크기를 크게 하면 되지 않을까?에 대한 고민을 해보면 좋을 것 같습니다.

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_heap_table_size

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_tmp_table_size

**Comment by yangroro** [comment]
@TaeGuNi 안녕하세요. 

네, 스터디 진행중에 group_concat 함수 사용시에 메모리 제한보다 더 큰 문자열을 다루게 되면 `Warning`을 보여준다고 해서 그렇다면 `Error`가 아닌 `Warning`을  보여주니 disk를 사용하지 않을까? 싶어서 생긴 궁금중이었습니다. 

친절한 설명 감사합니다.
