### ISSUE TITLE
[6-1]  쿼리에 `LIMIT`가 사용됐을때, `EXPLAIN`의 결과에서 `rows`컬럼의 오차가 큰 이유는?

### ISSUE THREAD

**Issue by JungleKim** [chocolate-factory/realmysql-study#8]
`EXPLAIN`의 결과로 나오는 `rows`는 실제로 Client에 반환되는 결과의 수가 아닌 Storage Engine에서 반환 될 것으로 예상되는 결과의 수인데, `LIMIT`를 쿼리에 사용하게 되면 `rows`값의 오차가 매우 심해진다고 한다.

그 이유는 무엇일까?

**Comment by demarlik01** [comment]
쿼리 실행 순서상 LIMIT이 맨 마지막에 실행 되기때문에... EXPLAIN의 결과값이 계산된후 LIMIT이 실행되기때문

**Comment by JungleKim** [comment]
`EXPLAIN`에서 노출되는 rows같은 경우는 최종적으로 사용자에게 리턴되는 카운트가 아니라 `스토리지 엔진`에서 `MySQL 엔진`에 전달하는 rows이다.

`LIMIT`를 사용할 경우 `스토리지 엔진`에서 전달 받은 값을 `LIMIT` 값 만큼 잘라서 사용자에게 반환하기 때문에 `EXPLAIN`의 값과 오차가 발생한다.
